### ISSUE TITLE
Unify wrappers into a single crate?

### ISSUE THREAD

**Issue by tarcieri** [RustCrypto/ring-compat#7]
Would it make sense to unify all of the *ring* wrappers into a single crate, with the algorithm-specific functionality gated behind cargo features?

I think that would make it easier to coordinate upgrades, especially for downstream users.

Also sidebar: I have some wrappers for ECDSA and Ed25519 signing/verification I'd like to upstream: https://github.com/iqlusioninc/signatory/tree/develop/signatory-ring/src

**Comment by newpavlov** [comment]
In this case I don't have any objections (and stakes), so feel free to move forward as you see fit. BTW it could be worth to use the `cryptography` crate here as was proposed by you earlier.

**Comment by tarcieri** [comment]
If I do move forward with this, I guess the next question is: what should we name it?

I think `ring-rustcrypto` would be fairly descriptive.

`ring-wrappers` would also be okay by me, albeit not super informative.

**Comment by newpavlov** [comment]
Personally I don't like using `rust` or `rs` in crate names. Regarding `ring-wrappers`, I think singular `ring-wrapper` would be better (though similarly undescriptive). We could use something like `rc-ring`, `rc` short for RustCrypto, it would indicate that this crate is not part of the ring project, but probably will be a bit more cryptic than `ring-wrapper`.

**Comment by tarcieri** [comment]
`rc-ring` sounds good to me, and I like using a prefix to indicate it isn't a "*ring* namespaced" crate.

A "clever" name (which we don't typically use) I thought of that might be fun is `ringer`, as in someone/something that looks like another.

**Comment by tarcieri** [comment]
How about `ring-compat`?

**Comment by tarcieri** [comment]
@newpavlov does the `ring-compat` name sound good to you? If so, I'd like to rename the existing crate, repos, and teams to that, and start integrating at least signature support

**Comment by newpavlov** [comment]
Yeah, no objections.

**Comment by tarcieri** [comment]
`ring-compat` v0.0.1 is released and contains a simple combination of `ring-aead` and `ring-digest`.

Some refactoring is definitely in order, but I'd otherwise say this issue is resolved.
