### ISSUE TITLE
Add support for PKCS#8 V1 keys for SigningKey

### ISSUE THREAD

**Issue by billguo99** [RustCrypto/ring-compat#83]
### Context
I want to create a [ring_compat::signature::ed25519::SigningKey](https://docs.rs/ring-compat/latest/ring_compat/signature/ed25519/struct.SigningKey.html) from a Ed25519 PKCS#8 v1 private key. The existing functions for `SigningKey` is for PKCS8#8 v2 private keys ([from_pkcs8](https://docs.rs/ring-compat/latest/ring_compat/signature/ed25519/struct.SigningKey.html#method.from_pkcs8)).

The `ring` crate supports PKCS#8 v1 keys by supplying the [from_pkcs8_maybe_unchecked](https://briansmith.org/rustdoc/ring/signature/struct.Ed25519KeyPair.html#method.from_pkcs8_maybe_unchecked) function.
So you can create  a ring::signature::[Ed25519KeyPair](https://briansmith.org/rustdoc/ring/signature/struct.Ed25519KeyPair.html#method.from_pkcs8_maybe_unchecked) using `from_pkcs8_maybe_unchecked` function but you cannot create the  `ring_compat::signature::ed25519::SigningKey` once you have the Ed25519KeyPair because the field of the `SigningKey` struct is private.

### Possible Solutions
1. add `from_pkcs8_maybe_unchecked` to implementations of `SigningKey` for ring-compat
2. create a constructor for `SigningKey` taking in Ed25519KeyPair

**Comment by tarcieri** [comment]
I think you want to open an issue on https://github.com/briansmith/ring instead

**Comment by billguo99** [comment]
Why do you want me to open an issue in the `ring` repo instead of here?
The [SigningKey](https://docs.rs/ring-compat/latest/ring_compat/signature/ed25519/struct.SigningKey.html) struct belongs to ring-compat.

**Comment by billguo99** [comment]
My apologies, I've reworded the issue above to be a bit more clear (hope it helps).

I tried using the `ed25519` crate's built-in `pkcs8` support:
1. I called ed25519::pkcs8::DecodePrivateKey::[read_pkcs8_pem_file](https://docs.rs/pkcs8/0.9.0/src/pkcs8/traits.rs.html#83) to read in my private key PKCS#8 v1 pem file.
```
let mut private_key_pem: KeypairBytes = DecodePrivateKey::read_pkcs8_pem_file(Path::new("./private.pem")).unwrap();
````
2. then I created `Ed25519KeyPair` from ring's functions
```
let keypair = Ed25519KeyPair::from_pkcs8_maybe_unchecked(&private_key_pem.secret_key).expect("Invalid Keypair");
``` 
3. but then I cannot create the `SigningKey` struct
```
let signing_key = SigningKey(keypair);
```
```
error[E0423]: cannot initialize a tuple struct which contains private fields
  --> src/main.rs:22:23
   |
22 |     let signing_key = SigningKey(keypair);
   |                       ^^^^^^^^^^
   |
note: constructor is not visible here due to private fields
  --> /home/bill/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-compat-0.4.1/src/signature/ed25519.rs:15:23
   |
15 | pub struct SigningKey(Ed25519KeyPair);
   |                       ^^^^^^^^^^^^^^ private field
```
-------------------------------------------

Is there perhaps a better crate you can recommend to sign API responses than the [ED25519](https://docs.rs/ed25519/latest/ed25519/) crate?

**Comment by tarcieri** [comment]
Aah sorry, I was suggesting a change to `ring-compat` to add support for the `pkcs8` crate's traits, using the internal implementation from the `ed25519` crate to ascertain whether or not the key is PKCS#8v1 or PKCS#8v2 (i.e. `OneAsymmetricKey`), and then calling the appropriate `ring` API to instantiate the inner key.
